insert into user (id,name,surname) values(1,'Marko', 'Marković');
insert into user (id,name,surname) values(2,'Milan', 'Milanović');
insert into user (id,name,surname) values(3,'Ivana', 'Ivanović');
insert into user (id,name,surname) values(4,'Iva', 'Ivić');
insert into airline (id,name,address,description) values (1,'AirSerbia','Batajnica','lowcost');
insert into airline (id,name,address,description) values (2,'AlItalia','Milano','lowcost');
insert into hotel (id,name,address,description) values (1,'Park','Novi Sad','Hotel sa 3 zvezdice');
insert into hotel (id,name,address,description) values (2,'Hajat','Beograd','Hotel sa 4 zvezdice');
insert into rentacar (id,name,address,description) values (1,'Easy car','Novi Sad','rent with class');
insert into rentacar (id,name,address,description) values (2,'Safe car','Beograd','safe rent');